// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockAlerts.Data;

namespace StockAlerts.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190531115403_Update013")]
    partial class Update013
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StockAlerts.Data.Model.AlertCriteria", b =>
                {
                    b.Property<Guid>("AlertCriteriaId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AlertDefinitionId");

                    b.Property<DateTimeOffset>("Created");

                    b.Property<decimal?>("Level");

                    b.Property<DateTimeOffset>("Modified");

                    b.Property<int>("Operator");

                    b.Property<Guid?>("ParentCriteriaId");

                    b.Property<int>("Type");

                    b.HasKey("AlertCriteriaId");

                    b.HasIndex("AlertDefinitionId")
                        .IsUnique()
                        .HasFilter("[AlertDefinitionId] IS NOT NULL");

                    b.HasIndex("ParentCriteriaId");

                    b.ToTable("AlertCriteria");
                });

            modelBuilder.Entity("StockAlerts.Data.Model.AlertDefinition", b =>
                {
                    b.Property<Guid>("AlertDefinitionId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AppUserId");

                    b.Property<DateTimeOffset>("Created");

                    b.Property<DateTimeOffset?>("LastSent");

                    b.Property<DateTimeOffset>("Modified");

                    b.Property<string>("Name");

                    b.Property<Guid?>("RootCriteriaId");

                    b.Property<int>("Status");

                    b.Property<Guid>("StockId");

                    b.HasKey("AlertDefinitionId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("StockId");

                    b.ToTable("AlertDefinitions");
                });

            modelBuilder.Entity("StockAlerts.Data.Model.AlertTriggerHistory", b =>
                {
                    b.Property<Guid>("AlertTriggerHistoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AlertDefinitionId");

                    b.Property<DateTimeOffset>("Created");

                    b.Property<DateTimeOffset>("Modified");

                    b.Property<DateTimeOffset>("TimeTriggered");

                    b.HasKey("AlertTriggerHistoryId");

                    b.HasIndex("AlertDefinitionId");

                    b.ToTable("AlertTriggerHistory");
                });

            modelBuilder.Entity("StockAlerts.Data.Model.ApiCall", b =>
                {
                    b.Property<Guid>("ApiCallId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Api");

                    b.Property<DateTimeOffset>("CallTime");

                    b.Property<DateTimeOffset>("Created");

                    b.Property<DateTimeOffset>("Modified");

                    b.Property<int>("ResponseCode");

                    b.Property<string>("Route");

                    b.HasKey("ApiCallId");

                    b.ToTable("ApiCalls");
                });

            modelBuilder.Entity("StockAlerts.Data.Model.AppUser", b =>
                {
                    b.Property<Guid>("AppUserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("Created");

                    b.Property<DateTimeOffset>("Modified");

                    b.Property<Guid>("UserId");

                    b.HasKey("AppUserId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("StockAlerts.Data.Model.Stock", b =>
                {
                    b.Property<Guid>("StockId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("Created");

                    b.Property<decimal>("LastPrice");

                    b.Property<DateTimeOffset>("LastTime");

                    b.Property<DateTimeOffset>("Modified");

                    b.Property<decimal>("PreviousLastPrice");

                    b.Property<string>("Symbol");

                    b.HasKey("StockId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("StockAlerts.Data.Model.UserPreferences", b =>
                {
                    b.Property<Guid>("UserPreferencesId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AppUserId");

                    b.Property<DateTimeOffset>("Created");

                    b.Property<string>("EmailAddress");

                    b.Property<DateTimeOffset>("Modified");

                    b.Property<bool>("ShouldSendEmail");

                    b.Property<bool>("ShouldSendPush");

                    b.Property<bool>("ShouldSendSms");

                    b.Property<string>("SmsNumber");

                    b.HasKey("UserPreferencesId");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("StockAlerts.Data.Model.AlertCriteria", b =>
                {
                    b.HasOne("StockAlerts.Data.Model.AlertDefinition", "AlertDefinition")
                        .WithOne("RootCriteria")
                        .HasForeignKey("StockAlerts.Data.Model.AlertCriteria", "AlertDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockAlerts.Data.Model.AlertCriteria", "ParentCriteria")
                        .WithMany("ChildrenCriteria")
                        .HasForeignKey("ParentCriteriaId");
                });

            modelBuilder.Entity("StockAlerts.Data.Model.AlertDefinition", b =>
                {
                    b.HasOne("StockAlerts.Data.Model.AppUser", "AppUser")
                        .WithMany("AlertDefinitions")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StockAlerts.Data.Model.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StockAlerts.Data.Model.AlertTriggerHistory", b =>
                {
                    b.HasOne("StockAlerts.Data.Model.AlertDefinition", "AlertDefinition")
                        .WithMany("AlertTriggerHistories")
                        .HasForeignKey("AlertDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StockAlerts.Data.Model.UserPreferences", b =>
                {
                    b.HasOne("StockAlerts.Data.Model.AppUser", "AppUser")
                        .WithOne("UserPreferences")
                        .HasForeignKey("StockAlerts.Data.Model.UserPreferences", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
